// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oahzvoxeujgxktgxywuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9haHp2b3hldWpneGt0Z3h5d3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDczNzAsImV4cCI6MjA2OTg4MzM3MH0.XPoUFr8llm9FhJHLR31pNGALbUbPOdbuG8q2hFlbx1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});